import 'package:auto_route/auto_route.dart';
import 'package:injectable/injectable.dart';

import '../../features/user/presentation/cubit/user/user_cubit.dart';
import '../di/di.dart';
import 'app_router.gr.dart'; // this is the file that is generated by the router generation process

@singleton
@AutoRouterConfig()
class AppRouter extends $AppRouter implements AutoRouteGuard {
  @override
  List<AutoRoute> get routes {
    final isAuthenticated = getIt<UserCubit>().state is UserStateLoggedIn;
    return [
      AutoRoute(page: LoginRoute.page, initial: !isAuthenticated),
      AutoRoute(page: SpeciesRoute.page, initial: isAuthenticated),
      AutoRoute(page: SpeciesDetailsRoute.page),
      AutoRoute(page: UserDetailsRoute.page),
    ];
  }

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final isAuthenticated = getIt<UserCubit>().state is UserStateLoggedIn;
    if (isAuthenticated || resolver.route.name == LoginRoute.name) {
      resolver.next(true);
    } else {
      resolver.redirect(const LoginRoute(), replace: true);
    }
  }
}
